### PR TITLE
Alternative implementation of loop transitions

### PR DESCRIPTION
**Pull request by rovo89**
Instead of finding a transition in the recorded polygon's points, look at the equally spaced points created from the polygon.

This fixes issues with sparse polygons (caused by map editing or with automatic point recording disabled). For dense polygons, which anyway have one point for every 10 cm, the result should be very similar as before.

### CODE REVIEW

**Comment by rovo89** [comment]
Based on #10.

Before:
image

After:
image

**Comment by rovo89** [comment]
I didn't test this in reality yet, but it looks good in the image. Maybe somebody already wants to have a look.

**Comment by rovo89** [comment]
Works fine with real grass as well ;)
Therefore I'd like to ask you to review and hopefully merge my changes, as a pre-requisite for https://github.com/ClemensElflein/open_mower_ros/pull/56 and manually edited maps.

**Comment by rovo89** [comment]
Added a fix for the orientation of the last point per loop, see https://discord.com/channels/958476543846412329/961804411112394842/1267589322878746726 for visual comparison and the lengthy discussion with Pete_MI632 before.

**Comment by rovo89** [comment]
(the bug seems to have existed before any of my changes)

**Comment by ClemensElflein** [comment]
Thank you for the PR, due to extracting the loop in a separate functions, the changes are hard to see

Note that `equally_spaced_points` does not generate new points it will only try to sample equally spaced points with roughly the specified distance from the input polyline.

**Comment by rovo89** [comment]
> Thank you for the PR, due to extracting the loop in a separate functions, the changes are hard to see

That's why I did the refactoring in a separate commit, which I even sent as a separate PR #10 in case there's disagreement on the logic to handle sparse maps 😉 But if you look at the individual commits in this PR, especially https://github.com/ClemensElflein/slic3r_coverage_planner/pull/11/commits/dfdf89f4ca72fa163f4f00e5929bfd8bc4152702, it should be more obvious what the change idea for the sparse points is.

**Comment by rovo89** [comment]
> Note that `equally_spaced_points` does not generate new points it will only try to sample equally spaced points with roughly the specified distance from the input polyline.

That contradicts my observations - I run a (partly) sparse map in production, and if the function didn't create new points, I would still see the problem that "2 points forward" sometimes means "several meters forward" (which is the main problem to be fixed in this PR).

Looking at the source code [here](https://github.com/ClemensElflein/Slic3r/blob/026c1380e0ad12176dd2fc8cdf8f6f181deeb071/xs/src/libslic3r/Polyline.cpp#L122-L124) and [here](https://github.com/ClemensElflein/Slic3r/blob/026c1380e0ad12176dd2fc8cdf8f6f181deeb071/xs/src/libslic3r/Line.cpp#L73-L90), it definitely looks like it's interpolating to generate new points e.g. at half the distance between two input points to reach exactly the requested distance.

**Comment by ClemensElflein** [comment]
Yes you are right, thank you for linking the sources. Then my memory was just wrong there, I could have sworn that I had discussed this already with someone.

Then it makes sense to do it like that. I'll look at the code in depth and try the PR on some test maps

**Comment by rovo89** [comment]
Thanks for considering it! Maybe this helps in checking the impact of the changes: https://github.com/rovo89/open_mower_ros/commits/svg/. It's a first version of a script which creates an SVG from the planning results. Just need to start the slic3r via the included launch file. For me, that helped a lot to quickly iterate.

**Comment by ClemensElflein** [comment]
Nice, we could do a CI job which generates SVG for some example maps for each PR on this repo. This way we could quickly see if new code breaks something in (somewhat) complicated maps

**Comment by ClemensElflein** [comment]
looks good on my test maps, I'll merge this. I have merged #10, but it has conflicts with this one, so I'll just take this one instead since it seems to include changes in #10 anyways.

**Comment by rovo89** [comment]
> looks good on my test maps, I'll merge this. I have merged #10, but it has conflicts with this one, so I'll just take this one instead since it seems to include changes in #10 anyways.

Ah, might be because you use squash-merging... I prefer rebase or merge commits because they keep the individual commits. As you noticed, looking at the overall diff can be overwhelming, but looking at the individual commits can make it much easier to follow the steps of the change. Depends on how the author works of course - if a PR has 10 commits with "changed this class" and "changed that other class", than there is less value in keeping them, but I tend to do e.g. refactoring first so that the actual change is better to see.

**Comment by rovo89** [comment]
> Nice, we could do a CI job which generates SVG for some example maps for each PR on this repo. This way we could quickly see if new code breaks something in (somewhat) complicated maps

Yes, I think we briefly chatted on that topic. That would mean to include some example maps and the planner result in the repo. If some code change leads to a different result, the check would fail. If the change was intended, then include the new result in the commit. Although the script would need some more improvements for that, and probably the check should be done on some other textual representation to avoid breaking it when only a color changes or something. The SVG could still be included to visualize the change, as in the screenshots above.

**Pull request merged**
